esphome:
  name: linda-hardware-test
  friendly_name: "Linda Hardware Test"
  platformio_options:
    board_build.flash_mode: qio
    board_build.psram_type: opi
  on_boot:
    priority: 600
    then:
      - switch.turn_on: lcd_power_switch
      - switch.turn_on: backlight_power_switch
      - delay: 100ms
      - switch.turn_on: backlight
      - logger.log: "Display power and backlight enabled"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: recommended
  flash_size: 16MB

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    ssid: "Linda-Test-AP"
    password: !secret ap_password

captive_portal:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: DEBUG

# ============================================
# Hardware Configuration
# ============================================

# SPI Bus for Display
spi:
  clk_pin: GPIO10
  mosi_pin: GPIO11

# I2C Bus for Touch
i2c:
  - id: bus_touch
    sda: GPIO6
    scl: GPIO7
    scan: false

# Power rails - CRITICAL: must enable these first!
output:
  - platform: gpio
    id: lcd_power
    pin: GPIO1

  - platform: gpio
    id: backlight_power
    pin: GPIO2

  - platform: gpio
    id: backlight_pwm
    pin: GPIO46

switch:
  - platform: output
    id: lcd_power_switch
    name: "LCD Power"
    output: lcd_power
    restore_mode: ALWAYS_ON

  - platform: output
    id: backlight_power_switch
    name: "Backlight Power"
    output: backlight_power
    restore_mode: ALWAYS_ON

  - platform: output
    id: backlight
    name: "Display Backlight"
    output: backlight_pwm
    restore_mode: ALWAYS_ON

light:
  # RGB LEDs
  - platform: neopixelbus
    id: rgb_leds
    type: GRB
    variant: WS2812
    pin: GPIO48
    num_leds: 5
    name: "Status LEDs"
    effects:
      - addressable_rainbow:
          name: "Rainbow"
          speed: 10
      - pulse:
          name: "Pulse"
          transition_length: 1s
          update_interval: 1s

# Rotary Encoder
sensor:
  - platform: rotary_encoder
    id: dial
    name: "Dial Position"
    pin_a: GPIO45
    pin_b: GPIO42
    resolution: 1
    on_clockwise:
      - logger.log: "Rotated clockwise"
      - light.addressable_set:
          id: rgb_leds
          range_from: 0
          range_to: 4
          color_brightness: 100%
          red: 0%
          green: 100%
          blue: 0%
    on_anticlockwise:
      - logger.log: "Rotated counter-clockwise"
      - light.addressable_set:
          id: rgb_leds
          range_from: 0
          range_to: 4
          color_brightness: 100%
          red: 100%
          green: 0%
          blue: 0%

# Encoder Button
binary_sensor:
  - platform: gpio
    id: dial_button
    name: "Dial Button"
    pin:
      number: GPIO41
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
    on_press:
      - logger.log: "Button pressed"
      - light.turn_on:
          id: rgb_leds
          effect: "Rainbow"
    on_release:
      - logger.log: "Button released"
      - light.turn_on:
          id: rgb_leds
          effect: "none"
          brightness: 50%
          red: 0%
          green: 0%
          blue: 100%
    on_click:
      min_length: 0ms
      max_length: 500ms
      then:
        - logger.log: "Short click detected"
    on_multi_click:
      - timing:
          - ON for at least 2s
        then:
          - logger.log: "Long press detected (2s)"
          - light.turn_off: rgb_leds

# ============================================
# Display using ESPHome's native GC9A01 support
# ============================================

display:
  - platform: ili9xxx
    model: GC9A01A
    id: main_display
    cs_pin: GPIO9
    dc_pin: GPIO3
    reset_pin: GPIO14
    dimensions:
      width: 240
      height: 240
    rotation: 0
    invert_colors: true
    update_interval: 50ms
    data_rate: 40MHz
    lambda: |-
      // Simple test - fill with green
      it.fill(Color(0x00, 0xFF, 0x00));

      // Draw red circle in center
      it.filled_circle(120, 120, 50, Color(0xFF, 0x00, 0x00));

      // Draw text
      it.printf(120, 120, id(font_large), Color(0xFF, 0xFF, 0xFF), TextAlign::CENTER, "TEST");

font:
  - file: "gfonts://Montserrat"
    id: font_small
    size: 16
  - file: "gfonts://Montserrat"
    id: font_medium
    size: 24
  - file: "gfonts://Montserrat"
    id: font_large
    size: 32

# Interval for periodic updates
interval:
  - interval: 5s
    then:
      - logger.log: "Hardware test running..."
