// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Main Screen

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Arc_Group = NULL;lv_obj_t *ui_Progress = NULL;lv_obj_t *ui_Temp_Bg = NULL;lv_obj_t *ui_Temp_Num_Bg = NULL;lv_obj_t *ui_Volume = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Arc_Group = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Arc_Group, 240);
lv_obj_set_height( ui_Arc_Group, 240);
lv_obj_set_align( ui_Arc_Group, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Arc_Group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Arc_Group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc_Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Arc_Group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Progress = lv_arc_create(ui_Arc_Group);
lv_obj_set_width( ui_Progress, 240);
lv_obj_set_height( ui_Progress, 240);
lv_obj_set_align( ui_Progress, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Progress, 15,35);
lv_arc_set_value(ui_Progress, 23);
lv_obj_set_style_radius(ui_Progress, 350, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Progress, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Progress, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Progress, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Progress, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Progress, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Progress, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Progress, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Progress, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Progress, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Progress, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Progress, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Progress, 15, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Progress, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Progress, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Temp_Bg = lv_obj_create(ui_Arc_Group);
lv_obj_set_width( ui_Temp_Bg, 200);
lv_obj_set_height( ui_Temp_Bg, 200);
lv_obj_set_align( ui_Temp_Bg, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Temp_Bg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Temp_Bg, 280, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Temp_Bg, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Temp_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Temp_Bg, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Temp_Bg, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Temp_Bg, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Temp_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Temp_Bg, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Temp_Bg, lv_color_hex(0x050A0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Temp_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Temp_Bg, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Temp_Bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_Temp_Bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_Temp_Bg, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temp_Num_Bg = lv_obj_create(ui_Temp_Bg);
lv_obj_set_width( ui_Temp_Num_Bg, 180);
lv_obj_set_height( ui_Temp_Num_Bg, 180);
lv_obj_set_align( ui_Temp_Num_Bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Temp_Num_Bg, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_remove_flag( ui_Temp_Num_Bg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Temp_Num_Bg, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Temp_Num_Bg, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Temp_Num_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Temp_Num_Bg, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Temp_Num_Bg, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Temp_Num_Bg, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Temp_Num_Bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Volume = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_Volume,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Volume, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Volume, 114);
lv_obj_set_height( ui_Volume, 10);
lv_obj_set_x( ui_Volume, 1 );
lv_obj_set_y( ui_Volume, 87 );
lv_obj_set_align( ui_Volume, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Volume,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Volume, lv_obj_get_style_pad_right(ui_Volume,LV_PART_MAIN) + 1, LV_PART_MAIN );

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Arc_Group= NULL;
ui_Progress= NULL;
ui_Temp_Bg= NULL;
ui_Temp_Num_Bg= NULL;
ui_Volume= NULL;

}
